--SQL Oracle
--1. SCRIPT ORACLE 19c
--Crear Tabla
CREATE TABLE ALUMNOS_L (
    ID_ALUMNO NUMBER GENERATED ALWAYS AS IDENTITY,
    CODIGO VARCHAR2(20),
    NOMBRE VARCHAR2(100),
    NOTA1 NUMBER(5,2),
    NOTA2 NUMBER(5,2),
    NOTA3 NUMBER(5,2),
    PROMEDIO NUMBER(5,2),
    ESTADO VARCHAR2(20),
    FECHA_REGISTRO DATE DEFAULT SYSDATE,

    CONSTRAINT PK_ALUMNOS PRIMARY KEY (ID_ALUMNO)
);

COMMIT;

--2. PROCEDIMIENTO ALMACENADO
CREATE OR REPLACE PROCEDURE INSERTAR_ALUMNO (
    P_CODIGO   IN VARCHAR2,
    P_NOMBRE   IN VARCHAR2,
    P_NOTA1    IN NUMBER,
    P_NOTA2    IN NUMBER,
    P_NOTA3    IN NUMBER
)
AS
    V_PROMEDIO NUMBER(5,2);
    V_ESTADO   VARCHAR2(20);
BEGIN

    V_PROMEDIO := (P_NOTA1 + P_NOTA2 + P_NOTA3) / 3;

    IF V_PROMEDIO >= 3.0 THEN
        V_ESTADO := 'APROBADO';
    ELSE
        V_ESTADO := 'REPROBADO';
    END IF;

    INSERT INTO ALUMNOS_L (
        CODIGO,
        NOMBRE,
        NOTA1,
        NOTA2,
        NOTA3,
        PROMEDIO,
        ESTADO
    )
    VALUES (
        P_CODIGO,
        P_NOMBRE,
        P_NOTA1,
        P_NOTA2,
        P_NOTA3,
        ROUND(V_PROMEDIO,2),
        V_ESTADO
    );

    COMMIT;

END;
/

COMMIT;

--3. CONSULTAR DATOS
SELECT * FROM ALUMNOS_L;
